#!/usr/bin/env python3
"""One-shot: add batch 2026-06-10 leads."""
import csv, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LEADS_CSV = ROOT / "docs" / "sales" / "leads.csv"

NEW_LEADS = [
    # --- SC / WV / OK ---
    {"practice_name": "Word Play Pediatric Therapies", "city": "Greenville", "state": "SC", "specialty": "Pediatric OT+PT+speech", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "wordplaykids@yahoo.com", "phone": "", "website": "https://www.wordplaykids.com", "source": "research 2026-06-10", "notes": "Pediatric PT, OT, speech. Greenville SC. Email from site."},
    {"practice_name": "Small Talk Pediatric Speech Therapy", "city": "Greenville", "state": "SC", "specialty": "Pediatric speech", "providers_estimate": "1-3", "owner_or_pm_name": "Lynne Willis", "title": "MA CCC-SLP/Founder", "email": "admin@smalltalksc.com", "phone": "", "website": "https://smalltalksc.com", "source": "research 2026-06-10", "notes": "Founder-SLP pediatric speech. Greenville SC. Email from site."},
    {"practice_name": "Pinnacle Physical Therapy & Personal Training", "city": "Columbia", "state": "SC", "specialty": "Physical therapy", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. JR Watts", "title": "Owner", "email": "pinnacleptcolumbia@outlook.com", "phone": "", "website": "https://pinnacleptcolumbia.com", "source": "research 2026-06-10", "notes": "Owner-PT. Columbia SC. Email from site."},
    {"practice_name": "Phoenix Physical Therapy Irmo", "city": "Irmo", "state": "SC", "specialty": "Physical therapy", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "irmo@phx-pt.com", "phone": "", "website": "https://phoenixphysicaltherapy.com", "source": "research 2026-06-10", "notes": "Independent PT. Columbia area SC. Email from location page."},
    {"practice_name": "Low Country Behavioral Health", "city": "Mount Pleasant", "state": "SC", "specialty": "Behavioral health (counseling)", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "info@lcbhealth.com", "phone": "", "website": "https://www.lcbhealth.com", "source": "research 2026-06-10", "notes": "Independent behavioral health. Mount Pleasant SC. Email from site."},
    {"practice_name": "Improve Physical Therapy & Hand Center", "city": "Charleston", "state": "WV", "specialty": "Physical therapy", "providers_estimate": "1-3", "owner_or_pm_name": "Todd Warner", "title": "PT, CHT/Owner", "email": "todd@improvept.com", "phone": "", "website": "https://improvept.com", "source": "research 2026-06-10", "notes": "Owner-PT. Charleston WV. Email from site."},
    {"practice_name": "Huntington Behavioral Health", "city": "Huntington", "state": "WV", "specialty": "Behavioral health (counseling)", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "amullins@hbhwv.com", "phone": "", "website": "https://hbhwv.com", "source": "research 2026-06-10", "notes": "Independent behavioral health. Huntington WV. Email from contact page."},
    {"practice_name": "Unbound Counseling LLC", "city": "Morgantown", "state": "WV", "specialty": "Behavioral health (counseling)", "providers_estimate": "1-3", "owner_or_pm_name": "", "title": "", "email": "info@unboundcounseling.org", "phone": "", "website": "https://www.unboundcounseling.org", "source": "research 2026-06-10", "notes": "Independent counseling. Morgantown WV. Email from contact page."},
    {"practice_name": "Blue Cardinal Counseling PLLC", "city": "Morgantown", "state": "WV", "specialty": "Behavioral health (counseling)", "providers_estimate": "1-3", "owner_or_pm_name": "Keegan Campbell", "title": "LICSW/Owner", "email": "keegan@bluecardinalcounseling.com", "phone": "", "website": "https://www.bluecardinalcounseling.com", "source": "research 2026-06-10", "notes": "Owner-led counseling. Morgantown WV. Email from site."},
    {"practice_name": "Coombs Family Chiropractic", "city": "Morgantown", "state": "WV", "specialty": "Chiropractic", "providers_estimate": "1-3", "owner_or_pm_name": "", "title": "", "email": "info@coombschiro.com", "phone": "", "website": "https://www.coombschiro.com", "source": "research 2026-06-10", "notes": "Independent chiro. Morgantown WV. Email from site."},
    {"practice_name": "Specialized Physical Therapy Services", "city": "Oklahoma City", "state": "OK", "specialty": "Physical therapy", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "specializedpts@gmail.com", "phone": "", "website": "https://www.specializedpts.com", "source": "research 2026-06-10", "notes": "Independent PT. OKC. Email from site."},
    {"practice_name": "Orthopedic Spine & Sports Physical Therapy", "city": "Moore", "state": "OK", "specialty": "Physical therapy", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "frontdesk@osspt.com", "phone": "", "website": "https://osspt.com", "source": "research 2026-06-10", "notes": "Orthopedic and sports PT. OKC area. Email from contact page."},
    {"practice_name": "Heinen Physical Therapy", "city": "Oklahoma City", "state": "OK", "specialty": "Physical therapy", "providers_estimate": "1-3", "owner_or_pm_name": "Lauren & Brice Heinen", "title": "DPT/Owners", "email": "contact@heinenpt.com", "phone": "", "website": "https://heinenpt.com", "source": "research 2026-06-10", "notes": "Owner-couple PT. OKC. Email from site."},
    {"practice_name": "Speech and Beyond Pediatric Therapy", "city": "Jenks", "state": "OK", "specialty": "Pediatric speech+OT", "providers_estimate": "1-3", "owner_or_pm_name": "Sarah Koehling", "title": "MS CCC-SLP/Owner", "email": "office@tulsaspeech.com", "phone": "", "website": "https://www.tulsaspeech.com", "source": "research 2026-06-10", "notes": "Owner-SLP pediatric speech and OT. Tulsa area OK. Email from site."},
    {"practice_name": "Reactivate Chiropractic and Rehab", "city": "Tulsa", "state": "OK", "specialty": "Chiropractic", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. David Fields", "title": "DC/Owner", "email": "contact@reactivatetherapy.com", "phone": "", "website": "https://reactivatetherapy.com", "source": "research 2026-06-10", "notes": "Owner-founded chiro + rehab. Tulsa OK. Email from site."},
    {"practice_name": "The SPOT for Kids", "city": "Broken Arrow", "state": "OK", "specialty": "Pediatric OT+PT+speech", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "admin@thespotforkids.com", "phone": "", "website": "https://www.thespotforkids.com", "source": "research 2026-06-10", "notes": "Pediatric PT, OT, speech. Tulsa suburb OK. Email from site."},

    # --- IA / MO / IN ---
    {"practice_name": "Integrated Physical Therapy & Sports Medicine", "city": "Des Moines", "state": "IA", "specialty": "Physical therapy", "providers_estimate": "3-5", "owner_or_pm_name": "Tate VanHouten", "title": "Owner", "email": "downtown@integratedptandsportsmed.com", "phone": "", "website": "https://www.integratedptandsportsmed.com", "source": "research 2026-06-10", "notes": "Owner-led PT. Des Moines IA. Email from site."},
    {"practice_name": "Kepros Physical Therapy & Performance", "city": "Cedar Rapids", "state": "IA", "specialty": "Physical therapy", "providers_estimate": "1-3", "owner_or_pm_name": "Ted Kepros", "title": "PT, MPT/Founder", "email": "info@keprospt.com", "phone": "", "website": "https://www.keprospt.com", "source": "research 2026-06-10", "notes": "Founder-PT. Cedar Rapids IA. Email from contact page."},
    {"practice_name": "Iowa Dermatology Consultants", "city": "Ankeny", "state": "IA", "specialty": "Dermatology", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "info@iowadermatologyconsultants.com", "phone": "", "website": "https://iowadermatologyconsultants.com", "source": "research 2026-06-10", "notes": "3-physician independent derm. Ankeny + Ames IA. Email from site."},
    {"practice_name": "Eastern Iowa Dermatology PLC", "city": "Bettendorf", "state": "IA", "specialty": "Dermatology", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Manish Kumar", "title": "MD/Founder", "email": "easterniowaderm@yahoo.com", "phone": "", "website": "https://www.easterniowaderm.com", "source": "research 2026-06-10", "notes": "Founder-physician derm. Bettendorf IA. Email from patient-information page."},
    {"practice_name": "St. Louis Dermatology Center", "city": "Clayton", "state": "MO", "specialty": "Dermatology", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "info@stlouisdermcenter.com", "phone": "", "website": "https://www.stlouisdermcenter.com", "source": "research 2026-06-10", "notes": "Independent derm. Clayton/St. Louis MO. Email from contact page."},
    {"practice_name": "Mid-County Dermatology", "city": "St. Louis", "state": "MO", "specialty": "Dermatology", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "info@midcountyderm.com", "phone": "", "website": "https://www.midcountyderm.com", "source": "research 2026-06-10", "notes": "2-physician independent derm. St. Louis MO. Email from homepage."},
    {"practice_name": "Active Life Chiropractic", "city": "Columbia", "state": "MO", "specialty": "Chiropractic", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Sam Henley", "title": "Owner", "email": "drsam@activelifechiro.net", "phone": "", "website": "https://activelifechiro.net", "source": "research 2026-06-10", "notes": "Owner-DC. Columbia MO. Email from site."},
    {"practice_name": "Compass Chiropractic & Wellness", "city": "Columbia", "state": "MO", "specialty": "Chiropractic", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Ashley Emel", "title": "Owner", "email": "office@compass-chiropractic.com", "phone": "", "website": "https://compass-chiropractic.com", "source": "research 2026-06-10", "notes": "Owner-DC. Columbia MO. Email from contact page."},
    {"practice_name": "IROC Physical Therapy", "city": "Indianapolis", "state": "IN", "specialty": "Physical therapy", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "staci@irocpt.com", "phone": "", "website": "https://irocpt.com", "source": "research 2026-06-10", "notes": "Independent PT. Indianapolis IN. Email from site."},
    {"practice_name": "Hand In Hand Comprehensive Therapy Specialists", "city": "Fort Wayne", "state": "IN", "specialty": "Pediatric OT+PT+speech", "providers_estimate": "3-5", "owner_or_pm_name": "Stephanie Furnas", "title": "Contact", "email": "info@handinhandtherapy.com", "phone": "", "website": "https://www.handinhandtherapy.com", "source": "research 2026-06-10", "notes": "Pediatric therapy. Fort Wayne IN. Email from site."},
    {"practice_name": "Hendricks Therapy", "city": "Plainfield", "state": "IN", "specialty": "Behavioral health (counseling)", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "staff@hendrickstherapy.com", "phone": "", "website": "https://www.hendrickstherapy.com", "source": "research 2026-06-10", "notes": "Independent counseling. Indianapolis suburb IN. Email from site."},
    {"practice_name": "Spencer Psychology", "city": "Bloomington", "state": "IN", "specialty": "Behavioral health (counseling)", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "admin@spencerpsychology.com", "phone": "", "website": "https://spencerpsychology.com", "source": "research 2026-06-10", "notes": "Independent psychology practice. Bloomington IN. Email from site."},

    # --- FL / AZ ---
    {"practice_name": "Body Mechanics Physical Therapy", "city": "Jacksonville", "state": "FL", "specialty": "Physical therapy", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Meghan Braun", "title": "PT DPT/Owner", "email": "care@bodymechpt.com", "phone": "", "website": "https://www.bodymechpt.com", "source": "research 2026-06-10", "notes": "Owner-PT. Jacksonville FL. Email from contact page."},
    {"practice_name": "Optimize Physical Therapy & Sports Performance", "city": "Jacksonville", "state": "FL", "specialty": "Physical therapy", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Jacob Evanich", "title": "DPT", "email": "lissan@optimizeptsport.com", "phone": "", "website": "https://optimizeptsport.com", "source": "research 2026-06-10", "notes": "Sports performance PT. Jacksonville FL. Email from contact page."},
    {"practice_name": "Movement Driven Performance Physiotherapy", "city": "Jacksonville", "state": "FL", "specialty": "Physical therapy", "providers_estimate": "1-3", "owner_or_pm_name": "", "title": "", "email": "info@movementdriven.com", "phone": "", "website": "https://www.movementdriven.com", "source": "research 2026-06-10", "notes": "Independent PT. Jacksonville FL. Email from contact page."},
    {"practice_name": "First Coast Dermatology", "city": "Jacksonville", "state": "FL", "specialty": "Dermatology", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Rosario", "title": "MD, FAAD", "email": "info@firstcoastdermatology.com", "phone": "", "website": "https://firstcoastdermatology.com", "source": "research 2026-06-10", "notes": "Independent derm. Jacksonville FL. Email from contact page."},
    {"practice_name": "Dedicated Pediatric Therapy", "city": "Fort Lauderdale", "state": "FL", "specialty": "Pediatric OT+speech", "providers_estimate": "3-5", "owner_or_pm_name": "Monica Belanger", "title": "OTR/L/CEO", "email": "therapy@dedicatedpediatrictherapy.com", "phone": "", "website": "https://www.dedicatedpediatrictherapy.com", "source": "research 2026-06-10", "notes": "CEO-led pediatric OT and speech. Fort Lauderdale FL. Email from location page."},
    {"practice_name": "Family First Therapy", "city": "Lutz", "state": "FL", "specialty": "Pediatric OT+PT+speech", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "info@familyfirsttherapyinc.com", "phone": "", "website": "https://www.familyfirsttherapyinc.com", "source": "research 2026-06-10", "notes": "Pediatric PT, OT, speech. Lutz FL. Email from contact page."},
    {"practice_name": "Gainesville Dermatology & Skin Surgery", "city": "Gainesville", "state": "FL", "specialty": "Dermatology", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "skinsurgery@gainesvilleflderm.com", "phone": "", "website": "https://www.gainesvilledermatologyskinsurgery.com", "source": "research 2026-06-10", "notes": "Independent derm. Gainesville FL. Email from contact page."},
    {"practice_name": "Arizona Skin Cancer Surgery Center", "city": "Tucson", "state": "AZ", "specialty": "Dermatology + Mohs", "providers_estimate": "1-3", "owner_or_pm_name": "Michael J. Huether", "title": "MD", "email": "appointments@azskincancer.com", "phone": "", "website": "https://www.azskincancer.com", "source": "research 2026-06-10", "notes": "Mohs + surgical derm. Tucson AZ. Email from contact page."},
    {"practice_name": "Phoenix Surgical Dermatology Group", "city": "Phoenix", "state": "AZ", "specialty": "Dermatology + Mohs", "providers_estimate": "3-5", "owner_or_pm_name": "Colleen Luna MD", "title": "MD/Owner", "email": "info@psdermgroup.com", "phone": "", "website": "https://www.psdermgroup.com", "source": "research 2026-06-10", "notes": "3-physician owner-operated surgical derm. Phoenix AZ. Email from contact page."},
    {"practice_name": "Alliance Physical Therapy Scottsdale", "city": "Scottsdale", "state": "AZ", "specialty": "Physical therapy", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "info@azalliancept.com", "phone": "", "website": "https://azalliancept.com", "source": "research 2026-06-10", "notes": "Independent PT. Scottsdale AZ. Email from site."},
    {"practice_name": "Corrective Physical Therapy", "city": "Scottsdale", "state": "AZ", "specialty": "Physical therapy", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Matt", "title": "Owner/PT", "email": "admin@correctivept.com", "phone": "", "website": "https://www.correctivept.com", "source": "research 2026-06-10", "notes": "Owner-PT. Scottsdale AZ. Email from site."},
    {"practice_name": "Way to Grow Pediatric Therapy", "city": "Chandler", "state": "AZ", "specialty": "Pediatric OT+speech+feeding", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "reception@waytogrowaz.com", "phone": "", "website": "https://waytogrowaz.com", "source": "research 2026-06-10", "notes": "Pediatric OT, speech, feeding. Chandler AZ. Email from site."},
    {"practice_name": "Ridge Zeller Therapy", "city": "Chandler", "state": "AZ", "specialty": "Pediatric speech+OT", "providers_estimate": "1-3", "owner_or_pm_name": "JoAnn Ridge & Meghan Zeller", "title": "Co-Directors/SLPs", "email": "contactus@rztherapy.com", "phone": "", "website": "https://ridgezellertherapy.com", "source": "research 2026-06-10", "notes": "Co-director SLPs. Pediatric speech and OT. Chandler AZ. Email from site."},

    # --- Rheumatology / ENT / Podiatry ---
    {"practice_name": "South Charlotte Rheumatology", "city": "Charlotte", "state": "NC", "specialty": "Rheumatology", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Firas Kassab", "title": "MD", "email": "info@scltrheum.com", "phone": "", "website": "https://southcharlotterheumatology.com", "source": "research 2026-06-10", "notes": "Independent rheumatology. Charlotte NC. Email from site."},
    {"practice_name": "Saint Louis Rheumatology", "city": "Webster Groves", "state": "MO", "specialty": "Rheumatology", "providers_estimate": "3-5", "owner_or_pm_name": "Dr. Chad Ronholm", "title": "MD", "email": "info@stlrheum.com", "phone": "", "website": "https://stlrheum.com", "source": "research 2026-06-10", "notes": "2-physician independent rheumatology. St. Louis area MO. Email from site."},
    {"practice_name": "Gateway ENT", "city": "St. Louis", "state": "MO", "specialty": "ENT (otolaryngology)", "providers_estimate": "3-5", "owner_or_pm_name": "Dr. Scott Hardeman", "title": "MD", "email": "officeadmin@gatewaydrs.com", "phone": "", "website": "https://gatewaydrs.com", "source": "research 2026-06-10", "notes": "4-physician independent ENT. St. Louis MO. Email from contact page."},
    {"practice_name": "Andros ENT & Sleep Center", "city": "Inver Grove Heights", "state": "MN", "specialty": "ENT (otolaryngology)", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Inell Rosario", "title": "MD", "email": "teagan@androsent-sleep.com", "phone": "", "website": "https://androsent-sleep.com", "source": "research 2026-06-10", "notes": "Independent ENT and sleep. MN suburb. Email from contact page."},
    {"practice_name": "Arizona Minimally Invasive Sinus Institute", "city": "Phoenix", "state": "AZ", "specialty": "ENT (otolaryngology)", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Robert Bridge", "title": "MD", "email": "officemanager@azmisi.com", "phone": "", "website": "https://www.azmisi.com", "source": "research 2026-06-10", "notes": "Independent ENT/sinus specialist. Phoenix AZ. Email from contact page."},
    {"practice_name": "Michigan Rheumatology & Wellness Center", "city": "Rochester Hills", "state": "MI", "specialty": "Rheumatology", "providers_estimate": "3-5", "owner_or_pm_name": "", "title": "", "email": "info@mirwc.com", "phone": "", "website": "https://www.mirwc.com", "source": "research 2026-06-10", "notes": "Independent rheumatology. Rochester Hills MI. Email from contact page."},
    {"practice_name": "Columbus Arthritis Center", "city": "Columbus", "state": "OH", "specialty": "Rheumatology", "providers_estimate": "5-10", "owner_or_pm_name": "", "title": "", "email": "info@columbusarthritis.com", "phone": "", "website": "https://columbusarthritis.com", "source": "research 2026-06-10", "notes": "Independent rheumatology. Columbus OH. Email from contact page."},
    {"practice_name": "Ladine Podiatry", "city": "Indianapolis", "state": "IN", "specialty": "Podiatry", "providers_estimate": "1-3", "owner_or_pm_name": "", "title": "", "email": "info@ladinepodiatry.net", "phone": "", "website": "https://www.ladinepodiatry.net", "source": "research 2026-06-10", "notes": "Independent podiatry. Indianapolis IN. Email from site."},
    {"practice_name": "North Tampa Foot Care", "city": "Tampa", "state": "FL", "specialty": "Podiatry", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Michal Waldman", "title": "DPM", "email": "drntfc@gmail.com", "phone": "", "website": "https://www.northtampafootcare.com", "source": "research 2026-06-10", "notes": "Owner-podiatrist. Tampa FL. Email from contact page."},
    {"practice_name": "Fitchburg Podiatry", "city": "Fitchburg", "state": "WI", "specialty": "Podiatry", "providers_estimate": "1-3", "owner_or_pm_name": "Dr. Mary Hickner", "title": "DPM/Owner", "email": "info@fitchburgpodiatry.com", "phone": "", "website": "https://www.fitchburgpodiatryllc.com", "source": "research 2026-06-10", "notes": "Owner-podiatrist. Madison area WI. Email from site."},
]


def main():
    with LEADS_CSV.open(newline="") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        existing_rows = list(reader)

    existing_practices = {r.get("practice_name", "").strip().lower() for r in existing_rows}
    existing_emails = {r.get("email", "").strip().lower() for r in existing_rows if r.get("email", "").strip()}

    to_add = []
    for lead in NEW_LEADS:
        name_key = lead["practice_name"].strip().lower()
        email_key = lead.get("email", "").strip().lower()
        if name_key in existing_practices:
            print(f"SKIP (dup name): {lead['practice_name']}")
            continue
        if email_key and email_key in existing_emails:
            print(f"SKIP (dup email): {lead['practice_name']} — {email_key}")
            continue
        to_add.append(lead)
        existing_practices.add(name_key)
        if email_key:
            existing_emails.add(email_key)

    if not to_add:
        print("Nothing new to add.")
        return

    with LEADS_CSV.open("a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        for lead in to_add:
            row = {field: "" for field in fieldnames}
            row.update(lead)
            row["STATUS"] = "📋 READY"
            writer.writerow(row)

    print(f"Added {len(to_add)} leads.")


if __name__ == "__main__":
    main()
