// CARC (Claim Adjustment Reason Code) human-readable descriptions.
//
// The 835 transaction only carries the numeric code; the description is
// reference data maintained by X12 and republished by CMS. We surface
// descriptions at ingest so reviewers don't have to look up codes manually.
//
// Source: full active X12 CARC list (005010X221A1 + post-publication updates
// through the 2025 maintenance cycle). Deactivated codes are included so
// older 835s with grandfathered codes still resolve.
//
// Codes are typically prefixed with the adjustment group code on the wire
// (CO = Contractual Obligation, OA = Other Adjustment, PI = Payer Initiated,
// PR = Patient Responsibility). lookupCarcReason strips the prefix before
// lookup so "CO-45", "CO45", "45", and "co_45" all resolve.

const CARC_REASONS: Record<string, string> = {
  "1": "Deductible amount.",
  "2": "Coinsurance amount.",
  "3": "Co-payment amount.",
  "4": "The procedure code is inconsistent with the modifier used.",
  "5": "The procedure code/type of bill is inconsistent with the place of service.",
  "6": "The procedure/revenue code is inconsistent with the patient's age.",
  "7": "The procedure/revenue code is inconsistent with the patient's gender.",
  "8": "The procedure code is inconsistent with the provider type/specialty (taxonomy).",
  "9": "The diagnosis is inconsistent with the patient's age.",
  "10": "The diagnosis is inconsistent with the patient's gender.",
  "11": "The diagnosis is inconsistent with the procedure.",
  "12": "The diagnosis is inconsistent with the provider type.",
  "13": "The date of death precedes the date of service.",
  "14": "The date of birth follows the date of service.",
  "15": "The authorization number is missing, invalid, or does not apply to the billed services or provider.",
  "16": "Claim/service lacks information or has submission/billing error(s).",
  "17": "Requested information was not provided or was insufficient/incomplete.",
  "18": "Exact duplicate claim/service.",
  "19": "This is a work-related injury/illness and thus the liability of the Worker's Compensation Carrier.",
  "20": "This injury/illness is covered by the liability carrier.",
  "21": "This injury/illness is the liability of the no-fault carrier.",
  "22": "This care may be covered by another payer per coordination of benefits.",
  "23": "The impact of prior payer(s) adjudication including payments and/or adjustments.",
  "24": "Charges are covered under a capitation agreement/managed care plan.",
  "26": "Expenses incurred prior to coverage.",
  "27": "Expenses incurred after coverage terminated.",
  "28": "Coverage not in effect at the time the service was provided.",
  "29": "The time limit for filing has expired.",
  "31": "Patient cannot be identified as our insured.",
  "32": "Our records indicate the patient is not an eligible dependent.",
  "33": "Insured has no dependent coverage.",
  "34": "Insured has no coverage for newborns.",
  "35": "Lifetime benefit maximum has been reached.",
  "39": "Services denied at the time authorization/pre-certification was requested.",
  "40": "Charges do not meet qualifications for emergent/urgent care.",
  "44": "Prompt-pay discount.",
  "45": "Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement.",
  "49": "This is a non-covered service because it is a routine/preventive exam or a diagnostic/screening procedure done in conjunction with a routine/preventive exam.",
  "50": "These are non-covered services because this is not deemed a 'medical necessity' by the payer.",
  "51": "These are non-covered services because this is a pre-existing condition.",
  "53": "Services by an immediate relative or a member of the same household are not covered.",
  "54": "Multiple physicians/assistants are not covered in this case.",
  "55": "Procedure/treatment/drug is deemed experimental/investigational by the payer.",
  "56": "Procedure/treatment has not been deemed 'proven to be effective' by the payer.",
  "58": "Treatment was deemed by the payer to have been rendered in an inappropriate or invalid place of service.",
  "59": "Processed based on multiple or concurrent procedure rules. (For example, multiple-surgery or diagnostic-imaging-concurrent-procedure rules.)",
  "60": "Charges for outpatient services are not covered when performed within a period of time prior to or after inpatient services.",
  "61": "Adjusted for failure to obtain second surgical opinion.",
  "66": "Blood deductible.",
  "69": "Day outlier amount.",
  "70": "Cost outlier — adjustment to compensate for additional costs.",
  "74": "Indirect Medical Education adjustment.",
  "75": "Direct Medical Education adjustment.",
  "76": "Disproportionate Share adjustment.",
  "78": "Non-Covered days/Room charge adjustment.",
  "85": "Patient interest adjustment (use only group code PR).",
  "87": "Transfer amount.",
  "89": "Professional fees removed from charges.",
  "90": "Ingredient cost adjustment.",
  "91": "Dispensing fee adjustment.",
  "94": "Processed in excess of charges.",
  "95": "Plan procedures not followed.",
  "96": "Non-covered charge(s).",
  "97": "The benefit for this service is included in the payment/allowance for another service/procedure that has already been adjudicated.",
  "100": "Payment made to patient/insured/responsible party.",
  "101": "Predetermination: anticipated payment upon completion of services or claim adjudication.",
  "102": "Major medical adjustment.",
  "103": "Provider promotional discount (e.g., senior citizen discount).",
  "104": "Managed care withholding.",
  "105": "Tax withholding.",
  "106": "Patient payment option/election not in effect.",
  "107": "The related or qualifying claim/service was not identified on this claim.",
  "108": "Rent/purchase guidelines were not met.",
  "109": "Claim/service not covered by this payer/contractor. You must send the claim/service to the correct payer/contractor.",
  "110": "Billing date predates service date.",
  "111": "Not covered unless the provider accepts assignment.",
  "112": "Service not furnished directly to the patient and/or not documented.",
  "114": "Procedure/product not approved by the Food and Drug Administration.",
  "115": "Procedure postponed, canceled, or delayed.",
  "116": "The advance indemnification notice signed by the patient did not comply with requirements.",
  "117": "Transportation is only covered to the closest facility that can provide the necessary care.",
  "118": "ESRD network support adjustment.",
  "119": "Benefit maximum for this time period or occurrence has been reached.",
  "121": "Indemnification adjustment — compensation for outstanding member responsibility.",
  "122": "Psychiatric reduction.",
  "125": "Submission/billing error(s).",
  "128": "Newborn's services are covered in the mother's allowance.",
  "129": "Prior processing information appears incorrect.",
  "130": "Claim submission fee.",
  "131": "Claim specific negotiated discount.",
  "132": "Prearranged demonstration project adjustment.",
  "133": "The disposition of the related claim/service is pending due to litigation.",
  "134": "Technical fees removed from charges.",
  "135": "Interim bills cannot be processed.",
  "136": "Failure to follow prior payer's coverage rules.",
  "137": "Regulatory surcharges, assessments, allowances or health-related taxes.",
  "138": "Appeal procedures not followed or time limits not met.",
  "139": "Contracted funding agreement — subscriber is employed by the provider of services.",
  "140": "Patient/Insured health identification number and name do not match.",
  "142": "Monthly Medicaid patient liability amount.",
  "143": "Portion of payment deferred.",
  "144": "Incentive adjustment (e.g., preferred product/service).",
  "146": "Diagnosis was invalid for the date(s) of service reported.",
  "147": "Provider contracted/negotiated rate expired or not on file.",
  "148": "Information from another provider was not provided or was insufficient/incomplete.",
  "149": "Lifetime benefit maximum has been reached for this service/benefit category.",
  "150": "Payer deems the information submitted does not support this level of service.",
  "151": "Payment adjusted because the payer deems the information submitted does not support this many/frequency of services.",
  "152": "Payer deems the information submitted does not support this length of service.",
  "153": "Payer deems the information submitted does not support this dosage.",
  "154": "Payer deems the information submitted does not support this day's supply.",
  "155": "Patient refused the service/procedure.",
  "157": "Service/procedure was provided as a result of an act of war.",
  "158": "Service/procedure was provided outside of the United States.",
  "159": "Service/procedure was provided as a result of terrorism.",
  "160": "Injury/illness was the result of an activity that is a benefit exclusion.",
  "161": "Provider performance bonus.",
  "162": "State-mandated requirement for property and casualty.",
  "163": "Attachment/other documentation referenced on the claim was not received.",
  "164": "Attachment/other documentation referenced on the claim was not received in a timely fashion.",
  "166": "These services were submitted after this payer's responsibility for processing claims under this plan ended.",
  "167": "This (these) diagnosis(es) is (are) not covered.",
  "169": "Alternate benefit has been provided.",
  "170": "Payment is denied when performed/billed by this type of provider.",
  "171": "Payment is denied when performed/billed by this type of provider in this type of facility.",
  "172": "Payment is adjusted when performed/billed by a provider of this specialty.",
  "173": "Service/equipment was not prescribed by a physician.",
  "174": "Service was not prescribed prior to delivery.",
  "175": "Prescription is incomplete.",
  "176": "Prescription is not current.",
  "177": "Patient has not met the required eligibility requirements.",
  "178": "Patient has not met the required spend-down requirements.",
  "179": "Patient has not met the required waiting requirements.",
  "180": "Patient has not met the required residency requirements.",
  "181": "Procedure code was invalid on the date of service.",
  "182": "Procedure modifier was invalid on the date of service.",
  "183": "The referring provider is not eligible to refer the service billed.",
  "184": "The prescribing/ordering provider is not eligible to prescribe/order the service billed.",
  "185": "The rendering provider is not eligible to perform the service billed.",
  "186": "Level of care change adjustment.",
  "187": "Consumer Spending Account payments (e.g., HRA, FSA).",
  "188": "This product/procedure is only covered when used according to FDA recommendations.",
  "189": "'Not otherwise classified' or 'unlisted' procedure code (CPT/HCPCS) was billed when there is a specific procedure code for this procedure/service.",
  "190": "Payment is included in the allowance for a Skilled Nursing Facility (SNF) qualified stay.",
  "192": "Non-standard adjustment code from paper remittance.",
  "193": "Original payment decision is being maintained. Upon review, it was determined that this claim was processed properly.",
  "194": "Anesthesia performed by the operating physician, the assistant surgeon, or the attending physician.",
  "195": "Refund issued to an erroneous priority payer for this claim/service.",
  "197": "Precertification/authorization/notification/pre-treatment absent.",
  "198": "Precertification/notification/authorization/pre-treatment exceeded.",
  "199": "Revenue code and procedure code do not match.",
  "200": "Expenses incurred during lapse in coverage.",
  "201": "Patient is responsible for amount of this claim/service through WC Medicare set-aside arrangement or other agreement.",
  "202": "Non-covered personal-comfort or convenience services.",
  "203": "Discontinued or reduced service.",
  "204": "This service/equipment/drug is not covered under the patient's current benefit plan.",
  "205": "Pharmacy discount card processing fee.",
  "206": "National Provider Identifier — missing.",
  "207": "National Provider Identifier — invalid format.",
  "208": "National Provider Identifier — not matched.",
  "209": "Per regulatory or other agreement: the provider cannot collect this amount from the patient.",
  "210": "Payment adjusted because pre-certification/authorization not received in a timely fashion.",
  "211": "National Drug Codes (NDC) not eligible for rebate, are not covered.",
  "212": "Administrative surcharges are not covered.",
  "213": "Non-compliance with the physician self-referral prohibition legislation or payer policy.",
  "215": "Based on subrogation of a third-party settlement.",
  "216": "Based on the findings of a review organization.",
  "219": "Based on extent of injury.",
  "222": "Exceeds the contracted maximum number of hours/days/units by this provider for this period.",
  "223": "Adjustment code for mandated federal, state or local law/regulation that is not already covered by another code and is mandated before a new code can be created.",
  "224": "Patient identification compromised by identity theft. Identity verification required for processing this and future claims.",
  "225": "Penalty or interest payment by payer (only used for plan-to-plan encounter reporting within the 837).",
  "226": "Information requested from the billing/rendering provider was not provided or was insufficient/incomplete.",
  "227": "Information requested from the patient/insured/responsible party was not provided or was insufficient/incomplete.",
  "228": "Denied for failure of this provider, another provider, or the subscriber to supply requested information to a previous payer for adjudication.",
  "229": "Partial charge amount not considered by Medicare due to the initial claim Type of Bill being 12X.",
  "231": "Mutually exclusive procedures cannot be done in the same day/setting.",
  "232": "Institutional Transfer Amount.",
  "233": "Services/charges related to the treatment of a hospital-acquired condition or preventable medical error.",
  "234": "This procedure is not paid separately.",
  "235": "Sales Tax.",
  "236": "This procedure or procedure/modifier combination is not compatible with another procedure or procedure/modifier combination provided on the same day according to the National Correct Coding Initiative or workers compensation state regulations/fee schedule requirements.",
  "237": "Legislated/Regulatory Penalty.",
  "238": "Claim spans eligible and ineligible periods of coverage; rebill separate claims.",
  "239": "Claim spans eligible and ineligible periods of coverage. Rebill separate claims.",
  "240": "The diagnosis is inconsistent with the patient's birth weight.",
  "241": "Low Income Subsidy (LIS) Co-payment Amount.",
  "242": "Services not provided by network/primary care providers.",
  "243": "Services not authorized by network/primary care providers.",
  "245": "Provider performance program withhold.",
  "246": "This non-payable code is for required reporting only.",
  "247": "Deductible for Professional service rendered in an Institutional setting and billed on an Institutional claim.",
  "248": "Coinsurance for Professional service rendered in an Institutional setting and billed on an Institutional claim.",
  "249": "This claim has been identified as a readmission.",
  "250": "The attachment/other documentation that was received was the incorrect attachment/document.",
  "251": "The attachment/other documentation that was received was incomplete or deficient.",
  "252": "An attachment/other documentation is required to adjudicate this claim/service.",
  "253": "Sequestration — reduction in federal payment.",
  "254": "Claim received by the dental plan, but benefits not available under this plan. Submit these services to the patient's medical plan for further consideration.",
  "256": "Service not payable per managed care contract.",
  "257": "The disposition of the claim/service is undetermined during the premium payment grace period per Health Insurance Exchange requirements.",
  "258": "Claim/service not covered when patient is in custody/incarcerated. Applicable federal, state or local authority may cover the claim/service.",
  "259": "Additional payment for Dental/Vision service utilization.",
  "260": "Processed under Medicaid ACA Enhanced Fee Schedule.",
  "261": "The procedure or service is inconsistent with the patient's history.",
  "262": "Adjustment for delivery cost.",
  "263": "Adjustment for shipping cost.",
  "264": "Adjustment for postage cost.",
  "265": "Adjustment for administrative cost.",
  "266": "Adjustment for compound preparation cost.",
  "267": "Claim/service spans multiple months.",
  "268": "The Claim spans two calendar years.",
  "269": "Anesthesia not covered for this service/procedure.",
  "270": "Claim received by the medical plan, but benefits not available under this plan. Submit these services to the patient's dental plan for further consideration.",
  "271": "Prior contractual reductions related to a current periodic payment as part of a contractual agreement.",
  "272": "Coverage/program guidelines were not met.",
  "273": "Coverage/program guidelines were exceeded.",
  "274": "Fee/Service not payable per patient Care Coordination arrangement.",
  "275": "Prior payer's (or payers') patient responsibility (deductible, coinsurance, co-payment) not covered.",
  "276": "Services denied by the prior payer(s) are not covered by this payer.",
  "277": "The disposition of the claim/service is undetermined during the premium payment grace period per Health Insurance Exchange requirements. You must send the claim/service to the patient.",
  "278": "Performance program proficiency requirements not met.",
  "279": "Services not provided by Preferred network providers.",
  "280": "Claim received by the medical plan, but benefits not available under this plan. Submit these services to the patient's Pharmacy plan for further consideration.",
  "281": "Deductible waived per contractual agreement.",
  "282": "The procedure/revenue code is inconsistent with the type of bill.",
  "283": "Attending provider is not eligible to provide direction of care.",
  "284": "Precertification/authorization/notification/pre-treatment number may be valid but does not apply to the billed services.",
  "285": "Appeal procedures not followed.",
  "286": "Appeal time limits not met.",
  "287": "Referral exceeded.",
  "288": "Referral absent.",
  "289": "Services considered under the dental and medical plans, benefits not available.",
  "290": "Claim received by the medical plan, but benefits not available under this plan. Submit these services to the patient's vision plan for further consideration.",
  "291": "Claim received by the medical plan, but benefits not available under this plan. Submit these services to the patient's behavioral health plan for further consideration.",
  "292": "Claim received by the medical plan, but benefits not available under this plan. Submit these services to the patient's hearing plan for further consideration.",
  "293": "Payment made to employer.",
  "294": "Long-term care claim filed past the period of coverage authorized.",
  "295": "Pharmacy Direct/Indirect Remuneration (DIR).",
  "296": "Precertification/authorization referral was not received in a timely fashion.",
  "297": "Claim received by the medical plan, but benefits not available under this plan. Claim has been forwarded to the patient's pharmacy plan for further consideration.",
  "298": "Claim received by the medical plan, but benefits not available under this plan. Claim has been forwarded to the patient's vision plan for further consideration.",
  "299": "The billing provider is not eligible to receive payment for the service billed.",
  "300": "Claim received by the Medical Plan, but benefits not available under this plan. Claim has been forwarded to the patient's hearing plan for further consideration.",
  "301": "Claim received by the medical plan, but benefits not available under this plan. Claim has been forwarded to the patient's dental plan for further consideration.",
  "302": "Precertification/notification/authorization/pre-treatment time limit has expired.",
  "303": "Prior payer's (or payers') patient responsibility (deductible, coinsurance, co-payment) not covered for Qualified Medicare and Medicaid Beneficiaries.",
  "304": "Claim received by the medical plan, but benefits not available under this plan. Claim has been forwarded to the patient's behavioral health plan for further consideration.",
  "305": "Patient is responsible only for the cost share for that period of coverage.",
  "306": "Co-payment adjustment for visit type/place of service.",
  "307": "Coinsurance adjustment for visit type/place of service.",
  "308": "Deductible adjustment for visit type/place of service.",

  // Codes maintained but deactivated by X12 — kept here so legacy 835s from
  // older payer systems still resolve to readable text rather than the
  // bare "Denial code X" fallback.
  "25": "Payment denied; the prior payer paid the maximum allowed amount.",
  "30": "Payment adjusted because the patient has not met the required eligibility, spend down, waiting, or residency requirements.",
  "36": "Balance does not exceed co-payment amount.",
  "37": "Balance does not exceed deductible.",
  "38": "Services not provided or authorized by designated (network/primary care) providers.",
  "41": "Discount agreed to in Preferred Provider contract.",
  "42": "Charges exceed our fee schedule or maximum allowable amount.",
  "43": "Gramm-Rudman reduction.",
  "46": "This (these) service(s) is (are) not covered.",
  "47": "This (these) diagnosis(es) is (are) not covered, missing, or are invalid.",
  "48": "This (these) procedure(s) is (are) not covered.",
  "52": "The referring/prescribing/rendering provider is not eligible to refer/prescribe/order/perform the service billed.",
  "57": "Payment denied/reduced because the payer deems the information submitted does not support this level of service, this many services, this length of service, this dosage, or this day's supply.",
  "62": "Payment denied/reduced for absence of, or exceeded, pre-certification/authorization.",
  "63": "Correction to a prior claim.",
  "64": "Denial reversed per Medical Review.",
  "65": "Procedure code was incorrect. This payment reflects the correct code.",
  "67": "Lifetime reserve days.",
  "68": "DRG weight.",
  "71": "Primary Payer amount.",
  "72": "Coinsurance day.",
  "73": "Administrative days.",
  "77": "Covered days.",
  "79": "Cost Report days.",
  "80": "Outlier days.",
  "81": "Discharges.",
  "82": "PIP days.",
  "83": "Total visits.",
  "84": "Capital adjustment.",
  "86": "Statutory adjustment.",
  "88": "Adjustment amount represents collection against receivable created in prior overpayment.",
  "92": "Claim paid in full.",
  "93": "No claim level adjustments.",
  "98": "The hospital must file the Medicare claim for this inpatient non-physician service.",
  "99": "Medicare Secondary Payer adjustment amount.",
  "113": "Payment denied because service/procedure was provided outside the United States or as a result of war.",
  "120": "Patient is covered by a managed care plan.",
  "123": "Payer refund due to overpayment.",
  "124": "Payer refund amount — not our patient.",
  "126": "Deductible — major medical.",
  "127": "Coinsurance — major medical.",
  "141": "Claim spans eligible and ineligible periods of coverage.",
  "145": "Premium payment withholding.",
  "156": "Flexible spending account payments.",
  "165": "Referral absent or exceeded.",
  "168": "Service(s) have been considered under the patient's medical plan.",
  "191": "Not a work-related injury/illness and thus not the liability of the workers' compensation carrier.",
  "196": "Claim/service denied based on prior payer's coverage determination.",
  "214": "Workers' Compensation claim adjudicated as non-compensable.",
  "217": "Based on payer reasonable and customary fees.",
  "218": "Based on entitlement to benefits.",
  "220": "The applicable fee schedule/fee database does not contain the billed code.",
  "221": "Workers' Compensation claim is under investigation.",
  "230": "No available or correlating CPT/HCPCS code to describe this service.",
  "244": "Payment reduced to zero due to litigation. Additional information will be sent following the conclusion of litigation.",
  "255": "The disposition of this service line is pending further review.",
};

function stripPrefix(code: string): string {
  // Common adjustment-group prefixes used in CARC codes on the wire.
  const m = code.match(/^(?:CO|OA|PI|PR|CR)[-_ ]?([A-Z]?\d+[A-Z]?)$/i);
  return m ? m[1]! : code.replace(/^[A-Z]+[-_ ]/, "");
}

/**
 * Return the human description for a CARC code, or null if unknown.
 * Accepts forms like "CO-45", "CO45", "co_45", "45", "OA-147", "PR-1".
 */
export function lookupCarcReason(code: string): string | null {
  if (!code) return null;
  const bare = stripPrefix(code.trim()).toUpperCase();
  return CARC_REASONS[bare] ?? null;
}
